### ISSUE TITLE
🐛 Bad request returned when end and start date are not the same

### ISSUE THREAD

**Issue by JvandeKraats** [DannyvanderKraan/azure-carbon-cli#14]
When I call the cli tool with values Start date: 2024-07-03 End date: 2024-07-31, the tool writes the error `Response status code does not indicate success: 400 (Bad Request)` to the .csv files.

If I run the tool with the --debug flag I can see the error as described [here](https://learn.microsoft.com/en-us/azure/carbon-optimization/troubleshooting#42-one-month-date-scope-supported-in-certain-api-report-types)
As we are using the type `ItemDetailsReport` the start and end date should be equal.

I propose we remove the from and to parameters as they are not useful right now.
Let's replace it with a `DateOnly` that captures the month (and the year) the user wants to receive information about.

**Comment by DannyvanderKraan** [comment]
@JvandeKraats  Yeah, I agree. Sounds fine for now.
